function appVersion = getAppVersion(rootFolder, entryPointFolder, temporaryDir)
    arguments
        rootFolder       char
        entryPointFolder char
        temporaryDir     char
    end

    appName = class.Constants.appName;

    appVersion = struct('machine',     '', ...
                        'matlab',      '', ...
                        'browser',     '', ...
                        'application', struct('name', appName,                       ...
                                              'release', class.Constants.appRelease, ...
                                              'version', class.Constants.appVersion, ...
                                              'rootFolder', rootFolder,              ...
                                              'entryPointFolder',  entryPointFolder, ...
                                              'tempSessionFolder', temporaryDir));

    if exist('ctfroot', 'file')
        appVersion.application.ctfRoot = ctfroot;
    end

    % OS
    appVersion.machine = struct('name',         'MACHINE',                                      ...
                                'platform',     appEngine.util.OperationSystem('platform'),     ...
                                'version',      appEngine.util.OperationSystem('ver'),          ...
                                'computerName', appEngine.util.OperationSystem('computerName'), ...
                                'userName',     appEngine.util.OperationSystem('userName'));

    % MATLAB    
    [matVersion, matReleaseDate] = version;
    matProducts = struct2table(ver);
    appVersion.matlab = struct('name',          'MATLAB',                                                       ...
                               'version',       sprintf('%s (Release date: %s)', matVersion, matReleaseDate),   ...
                               'pid',           feature('getpid'),                                              ...
                               'rootPath',      matlabroot,                                                     ...
                               'products',      strjoin(matProducts.Name + " v. " + matProducts.Version, ', '), ...
                               'numWorkers',    1);
    
    p = gcp("nocreate");
    if ~isempty(p)
        appVersion.matlab.numWorkers = p.NumWorkers;
    end
end