classdef (Abstract) Controller

    % Trata-se de classe abstrata, cujo método Run cria as variáveis requeridas
    % pelo biblioteca reportLib, de SupportPackages. São elas:
    % • reportInfo....: estrutura com os campos obrigatórios "App", "Version", 
    %   "Path", "Model" e "Function". Campos opcionais podem ser criados.

    % • dataOverview..: lista de estruturas com os campos obrigatórios "ID", 
    %   "InfoSet" e "HTML". Em "InfoSet", armazena-se um handle para instância 
    %   da classe model.ECD. As instância desse classe são agrupadas por CNPJ 
    %   e ordenadas pelo fim do PERÍODO CONTÁBIL.

    % • analyzedData..: instância de dataOverview (imaginando que dataOverview 
    %   é a variável que possibilita a recorrência).

    % Quando o objeto criado é uma IMAGEM, tem-se:
    % • imgSettings.: campo extraído do script .JSON que norteia a criação
    %   do relatório, o qual é uma estrutura com os campos "Origin", "Source", 
    %   "Caption", "Settings", "Intro", "Error" e "LineBreak".
    
    % Quando o objeto criado uma TABELA, tem-se:
    % • tableSettings.: campo extraído do script .JSON que norteia a criação
    %   do relatório, o qual é uma estrutura com os campos "Origin", "Source", 
    %   "Columns", "Caption", "Settings", "Intro", "Error" e "LineBreak".

    properties (Constant)
        %-----------------------------------------------------------------%
        docVersion = dictionary( ...
            ["Preliminar", "Definitiva"], ...
            ["preview", "final"] ...
        )
    end

    methods (Static)
        %-----------------------------------------------------------------%
        function Run(mainApp, callingApp, context, ecdObj)
            arguments
                mainApp
                callingApp
                context {mustBeMember(context, {'FILE', 'ECD'})}
                ecdObj
            end

            appName = class.Constants.appName;
            projectData = mainApp.projectData;
            generalSettings = mainApp.General;
            rootFolder = mainApp.rootFolder;

            [projectFolder, ...
             programDataFolder] = appEngine.util.Path(appName, rootFolder);

            issueId = num2str(projectData.modules.(context).ui.issue);
            docName = projectData.modules.(context).ui.reportModel;
            docIndex = find(strcmp({projectData.report.templates.Name}, docName), 1);
            if isempty(docIndex)
                error('reportLibConnection:Controller', 'Pendente escolha do modelo de relatório.')
            end

            docType = projectData.report.templates(docIndex).DocumentType;
            docVersion = reportLibConnection.Controller.docVersion(projectData.modules.(context).ui.reportVersion);

            try
                if ~isdeployed()
                    error('reportLibConnection:Controller', 'ForceDebugMode')
                end
                docScript = jsondecode(fileread(fullfile(programDataFolder, 'ReportTemplates', projectData.report.templates(docIndex).File)));
            catch
                docScript = jsondecode(fileread(fullfile(projectFolder,     'ReportTemplates', projectData.report.templates(docIndex).File)));
            end

            %-------------------------------------------------------------%
            % reportInfo
            %
            % Importante observar que o campo "Function" armazena informações
            % gerais, a compor itens "Introdução", "Metodologia" e "Conclusão",
            % e informações específicas, a compor itens com recorrências, como 
            % "Resultados".
            %-------------------------------------------------------------%
            reportInfo = struct('App',      mainApp, ...
                                'Version',  generalSettings.AppVersion, ...
                                'Path',     struct('rootFolder',                         rootFolder, ...
                                                   'userFolder',                         generalSettings.fileFolder.userPath, ...
                                                   'tempFolder',                         generalSettings.fileFolder.tempPath, ...
                                                   'appConnection',                      projectFolder, ...
                                                   'appDataFolder',                      programDataFolder), ...
                                'Model',    struct('Name',                               docName, ...
                                                   'DocumentType',                       docType, ...
                                                   'Script',                             docScript, ...
                                                   'Version',                            docVersion), ...
                                'Function', struct(...
                                                   ... % APLICÁVEIS ÀS SEÇÕES GERAIS DO RELATÓRIO
                                                   'cfg_FILE',                          'reportLibConnection.Variable.GeneralSettings(reportInfo, "FILE+ReportTemplate")', ...
                                                   'cfg_ECD',                           'reportLibConnection.Variable.GeneralSettings(reportInfo, "ECD+ReportTemplate")', ...
                                                   ...
                                                   'var_Issue',                          issueId, ...
                                                   'var_Unit',                           projectData.modules.(context).ui.unit, ...
                                                   'var_EntityGroupType',                projectData.modules.(context).ui.entity.type, ...
                                                   'var_EntityGroupName',                projectData.modules.(context).ui.entity.name, ...
                                                   'var_EntityGroupId',                  projectData.modules.(context).ui.entity.id, ...
                                                   ...
                                                   'eFiscaliza_solicitacaoId',          'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "id")', ...
                                                   'eFiscaliza_solicitacaoCodigo',      'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "codigo")', ...
                                                   'eFiscaliza_solicitacaoDescricao',   'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "descricao")', ...
                                                   'eFiscaliza_solicitacaoStatus',      'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "status")', ...
                                                   'eFiscaliza_solicitacaoDataInicio',  'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "inicio")', ...
                                                   'eFiscaliza_solicitacaoDataFim',     'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "fim")', ...
                                                   'eFiscaliza_solicitacaoDemandante',  'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "demandante")', ...
                                                   'eFiscaliza_solicitacaoPAAF',        'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "paaf")', ...
                                                   'eFiscaliza_solicitacaoTipo',        'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "tipo")', ...
                                                   'eFiscaliza_solicitacaoTema',        'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "tema")', ...
                                                   'eFiscaliza_solicitacaoSubtema',     'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "subtema")', ...
                                                   'eFiscaliza_solicitacaoTematica',    'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "tematica")', ...
                                                   'eFiscaliza_solicitacaoMacrotema',   'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "macrotema")', ...
                                                   'eFiscaliza_solicitacaoClasse',      'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "classe")', ...
                                                   'eFiscaliza_solicitacaoSeiProcesso', 'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "processo")', ...
                                                   'eFiscaliza_solicitacaoEntidades',   'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "entidades")', ...
                                                   'eFiscaliza_solicitacaoServicos',    'reportLib.getEFiscalizaIssueParameter(reportInfo, "Solicitação de Inspeção", "servicos")', ...
                                                   ...
                                                   'eFiscaliza_acaoId',                 'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "id")', ...
                                                   'eFiscaliza_acaoCodigo',             'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "codigo")', ...
                                                   'eFiscaliza_acaoDescricao',          'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "descricao")', ...
                                                   'eFiscaliza_acaoStatus',             'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "status")', ...
                                                   'eFiscaliza_acaoDataInicio',         'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "inicio")', ...
                                                   'eFiscaliza_acaoDataFim',            'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "fim")', ...
                                                   'eFiscaliza_acaoUnidade',            'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "unidade")', ...
                                                   'eFiscaliza_acaoResponsavel',        'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "responsavel")', ...
                                                   'eFiscaliza_acaoSeiProcesso',        'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "processo")', ...
                                                   'eFiscaliza_acaoSeiRelatorio',       'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "relatorio")', ...
                                                   'eFiscaliza_acaoSeiDespacho',        'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "despacho")', ...
                                                   'eFiscaliza_acaoSeiPado',            'reportLib.getEFiscalizaIssueParameter(reportInfo, "Ação de Inspeção",        "pado")', ...
                                                   ...
                                                   'eFiscaliza_atividadeId',            'reportLib.getEFiscalizaIssueParameter(reportInfo, "Atividade de Inspeção",   "id")', ...
                                                   'eFiscaliza_atividadeCodigo',        'reportLib.getEFiscalizaIssueParameter(reportInfo, "Atividade de Inspeção",   "codigo")', ...
                                                   'eFiscaliza_atividadeDescricao',     'reportLib.getEFiscalizaIssueParameter(reportInfo, "Atividade de Inspeção",   "descricao")', ...
                                                   'eFiscaliza_atividadeStatus',        'reportLib.getEFiscalizaIssueParameter(reportInfo, "Atividade de Inspeção",   "status")', ...
                                                   'eFiscaliza_atividadeDataInicio',    'reportLib.getEFiscalizaIssueParameter(reportInfo, "Atividade de Inspeção",   "inicio")', ...
                                                   'eFiscaliza_atividadeDataFim',       'reportLib.getEFiscalizaIssueParameter(reportInfo, "Atividade de Inspeção",   "fim")', ...
                                                   'eFiscaliza_atividadeFiscalLider',   'reportLib.getEFiscalizaIssueParameter(reportInfo, "Atividade de Inspeção",   "principal")', ...
                                                   ...
                                                   'eFiscaliza_Demandante',             'reportLib.getEFiscalizaIssueParameter(reportInfo, "Nome do Demandante")', ...
                                                   'eFiscaliza_UnidadeExecutante',      'reportLib.getEFiscalizaIssueParameter(reportInfo, "Nome da Unidade Executante")', ...
                                                   'eFiscaliza_SedeUnidade',            'reportLib.getEFiscalizaIssueParameter(reportInfo, "Sede da Unidade Executante")', ...
                                                   'eFiscaliza_PeriodoPrevisto',        'reportLib.getEFiscalizaIssueParameter(reportInfo, "Período Previsto da Fiscalização")', ...
                                                   'eFiscaliza_ListaFiscais',           'reportLib.getEFiscalizaIssueParameter(reportInfo, "Lista de Fiscais")', ...
                                                   ...
                                                   ... % APLICÁVEIS À SEÇÃO COM RECORRÊNCIA DO RELATÓRIO (exceto "var_Year", "tbl_FileByCompany")
                                                   ... % 'var_Index'
                                                   'var_Id',                            'analyzedData.ID', ...
                                                   "var_Year",                          'reportLibConnection.Variable.GeneralSettings(reportInfo, "Year")', ...
                                                   'var_NumFilesGlobal',                'numel(analyzedData.InfoSet.ecdObj)', ...
                                                   'var_NumFiles',                      'reportLibConnection.Variable.ClassProperty(analyzedData, "NumFiles")', ...
                                                   'var_FileNameList',                  'reportLibConnection.Variable.ClassProperty(analyzedData, "FileNameList")', ...
                                                   'var_EntityName',                    'reportLibConnection.Variable.ClassProperty(analyzedData, "CompanyName")', ...
                                                   'var_EntityId',                      'reportLibConnection.Variable.ClassProperty(analyzedData, "CompanyId")', ...
                                                   'var_EntityState',                   'reportLibConnection.Variable.ClassProperty(analyzedData, "State")', ...
                                                   'var_Hash',                          'reportLibConnection.Variable.ClassProperty(analyzedData, "Hash")', ...
                                                   'var_Period',                        'reportLibConnection.Variable.ClassProperty(analyzedData, "Period")', ...
                                                   'var_ReceitaFederal',                'reportLibConnection.Variable.ClassProperty(analyzedData, "ReceitaFederal")', ...
                                                   'var_ContentSample',                 'reportLibConnection.Variable.ClassProperty(analyzedData, "ContentSample")', ...
                                                   'var_Layout',                        'reportLibConnection.Variable.ClassProperty(analyzedData, "Layout")', ...
                                                   'var_NumAccount',                    'reportLibConnection.Variable.ClassProperty(analyzedData, "NumAccount")', ...
                                                   'var_TotalValue',                    'reportLibConnection.Variable.ClassProperty(analyzedData, "TotalValue")', ...
                                                   'tbl_FileByCompany',                 'reportLibConnection.Table.FileByCompany(reportInfo)', ...
                                                   'tbl_SourceFileStatus',              'reportLibConnection.Table.SourceFileStatus(analyzedData)', ...
                                                   'tbl_FileMetadata',                  'reportLibConnection.Table.FileMetadata(analyzedData)', ...
                                                   'tbl_Raw',                           'reportLibConnection.Table.Raw(reportInfo, analyzedData, tableSettings)', ...
                                                   'tbl_TabelaApuracao',                'reportLibConnection.Table.TabelaApuracao(analyzedData)', ...
                                                   'tbl_TabelaAnotacao_All',            'reportLibConnection.Table.TabelaAnotacao(analyzedData, "all")', ...
                                                   'tbl_TabelaAnotacao_On',             'reportLibConnection.Table.TabelaAnotacao(analyzedData, "on")'), ...
                                'Project',  projectData, ...
                                'Context',  context, ...
                                'Object',   ecdObj, ...
                                'Settings', generalSettings);

            fieldsUnnecessary = {'rootFolder', 'entryPointFolder', 'tempSessionFolder', 'ctfRoot'};
            fieldsUnnecessary(cellfun(@(x) ~isfield(reportInfo.Version.application, x), fieldsUnnecessary)) = [];
            if ~isempty(fieldsUnnecessary)
                reportInfo.Version.application = rmfield(reportInfo.Version.application, fieldsUnnecessary);
            end

            %-------------------------------------------------------------%
            % dataOverview
            %
            % Caso dataOverview não seja escalar e exista um item no relatório
            % com recorrência, a própria lib cria a variável "var_Index", acessível 
            % em "reportInfo.Function.var_Index".
            %-------------------------------------------------------------%
            dataOverview = struct('ID', {}, 'InfoSet', {}, 'HTML', {});

            idsList = {ecdObj.CompanyId};
            ids = unique(idsList);

            for id = ids
                idIndexes   = find(strcmp(idsList, id));
                [~, idSort] = sort(arrayfun(@(x) x.Period(2), ecdObj(idIndexes)));
                idIndexes   = idIndexes(idSort);

                nireInfo  = '';
                if ~isempty(ecdObj(idIndexes(1)).CompanyInfo.NIRE)
                    nireInfo = sprintf('%s - ', ecdObj(idIndexes(1)).CompanyInfo.NIRE);
                end
                companyId = sprintf('%s - %s%s', ecdObj(idIndexes(1)).CompanyId, nireInfo, ecdObj(idIndexes(1)).CompanyName);

                dataOverview(end+1) = struct('ID',      companyId,                           ...
                                             'InfoSet', struct('indexes', idIndexes,         ...
                                                               'ecdObj', ecdObj(idIndexes)), ...
                                             'HTML',    struct('Component', {}, 'Source', {}, 'Value', {}));
            end

            %-------------------------------------------------------------%
            % Conexão com reportLib, parte do repositório "SupportPackages"
            %-------------------------------------------------------------%
            HTMLDocContent = reportLib.Controller(reportInfo, dataOverview);

            %-------------------------------------------------------------%
            % Exclui container criado para os plots, caso aplicável.
            %-------------------------------------------------------------%
            hFigure    = mainApp.UIFigure;
            hContainer = findobj(hFigure, 'Tag', 'reportGeneratorContainer');
            if ~isempty(hContainer)
                delete(hContainer)
            end

            %-------------------------------------------------------------%
            % Em sendo a versão "Preliminar", apenas apresenta o html no
            % navegador. Por outro lado, em sendo a versão "Definitiva",
            % salva-se o arquivo ZIP em pasta local.
            %-------------------------------------------------------------%
            correlationKey     = char(matlab.lang.internal.uuid());
            sharepointFileBase = sprintf('%s_%s_%s',  appName, datestr(now, 'yyyymmdd'), correlationKey);
            [~, zipFileBase]   = appEngine.util.DefaultFileName('', [appName '_FinalReport'], issueId);

            HTMLFile = fullfile(generalSettings.fileFolder.tempPath, [sharepointFileBase '.html']);
            writematrix(HTMLDocContent, HTMLFile, 'QuoteStrings', 'none', 'FileType', 'text', 'Encoding', 'UTF-8')

            switch docVersion
                case 'preview'
                    web(HTMLFile, '-new')
                    updateGeneratedFiles(projectData, context)

                case 'final'
                    try
                        [issueDetails, msgError] = getOrFetchIssueDetails(projectData, projectData.modules.(context).ui.system, projectData.modules.(context).ui.issue, mainApp.eFiscalizaObj);
                        if ~isempty(msgError)
                            error('reportLibConnection:Controller', msgError)
                        end
                    catch ME
                        if ~isdeployed()
                            issueDetails = struct('usuario', struct('nome', 'NOME_FISCAL', 'email', 'EMAIL_FISCAL@anatel.gov.br', 'unidade', 'LOTACAO_FISCAL', 'funcao', 'FISCAL'));
                        else
                            rethrow(ME)
                        end
                    end

                    JSONFile  = '';
                    TEAMSFile = '';
                    XLSXFile  = '';
                    RAWFiles  = {};
                    ZIPFile   = ui.Dialog(callingApp.UIFigure, 'uiputfile', '', {'*.zip', [appName ' (*.zip)']}, fullfile(generalSettings.fileFolder.userPath, [zipFileBase '.zip']));
                    if isempty(ZIPFile)
                        return
                    end

                    ZIPFileList = {HTMLFile};

                    if strcmp(context, 'ECD')
                        JSONFile     = fullfile(generalSettings.fileFolder.tempPath, [sharepointFileBase '.json']);
                        TEAMSFile    = fullfile(generalSettings.fileFolder.tempPath, [sharepointFileBase '.teams']);

                        JSONContent  = reportLibConnection.Table.scarabJsonFile(projectData, context, ecdObj, correlationKey, mainApp.executionMode, issueDetails);
                        TEAMSContent = reportLibConnection.Table.scarabTeamsFileContent(issueDetails, sharepointFileBase);

                        writematrix(JSONContent,  JSONFile,  "FileType", "text", "QuoteStrings", "none", "WriteMode", "overwrite", "Encoding", "UTF-8")
                        writematrix(TEAMSContent, TEAMSFile, "FileType", "text", "QuoteStrings", "none", "WriteMode", "overwrite", "Encoding", "UTF-8")

                        ZIPFileList = [ZIPFileList, {JSONFile, TEAMSFile}];
                    end
                    
                    zip(ZIPFile, ZIPFileList)

                    switch context
                        case 'FILE'
                            generatedFileId = model.ProjectBase.computeReportFileInventoryHash(ecdObj);
                        case 'ECD'
                            generatedFileId = model.ProjectBase.computeReportAnalysisResultsHash(ecdObj);
                    end
                    updateGeneratedFiles(projectData, context, generatedFileId, RAWFiles, HTMLFile, JSONFile, XLSXFile, TEAMSFile, ZIPFile)
            end
        end
    end
end