classdef Project < handle

    properties
        %-----------------------------------------------------------------%
        name
        file
        hash

        modules
        report = struct('templates', [], 'settings',  [])
        
        issueDetails = struct('system', {}, 'issue', {}, 'details', {}, 'timestamp', {})
        entityDetails = struct('id', {}, 'details', {}, 'timestamp', {})

        inss
    end

    
    properties (Access = private)
        %-----------------------------------------------------------------%
        mainApp
        rootFolder
    end


    methods
        %-----------------------------------------------------------------%
        function obj = Project(mainApp, rootFolder)
            obj.mainApp = mainApp;
            obj.rootFolder = rootFolder;
            obj.inss = model.ProjectBase.readInssReferenceData(rootFolder);
            restart(obj)
        end

        %-----------------------------------------------------------------%
        % ## LIFECYCLE MANAGEMENT ##
        %-----------------------------------------------------------------%
        function restart(obj, context)
            contextList = {'FILE', 'ECD'};
            contextInitialization(obj, contextList, obj.mainApp.General)
        end

        %-----------------------------------------------------------------%
        function updateNeeded = checkIfUpdateNeeded(obj, ecdObj)
            updateNeeded = false;
            
            if ~isempty(obj.name)
                currentPrjHash = model.ProjectBase.computeProjectHash(obj.name, obj.file, ecdObj, obj.issueDetails, obj.entityDetails);
                updateNeeded   = ~isequal(obj.hash, currentPrjHash);
            end
        end

        %-----------------------------------------------------------------%
        function save(obj, context, prjName, prjFile, outputFileCompressionMode, ecdObj)
            arguments
                obj
                context (1,:) char {mustBeMember(context, {'FILE', 'ECD'})}
                prjName
                prjFile
                outputFileCompressionMode
                ecdObj
            end

            source    = class.Constants.appName;
            type      = 'ProjectData';
            version   = 1;
            userData  = [];

            prjHash  = model.ProjectBase.computeProjectHash(prjName, prjFile, ecdObj, obj.issueDetails, obj.entityDetails);
            variables = struct( ...
                'name',    prjName, ...
                'hash',    prjHash, ...
                'modules', obj.modules, ...
                'issueDetails', obj.issueDetails, ...
                'entityDetails', obj.entityDetails, ...
                'ecdData', ecdObj ...
            );

            compressionMode = '';
            if strcmp(outputFileCompressionMode, 'Não')
                compressionMode = '-nocompression';
            end

            save(prjFile, 'source', 'type', 'version', 'variables', 'userData', '-mat', '-v7', compressionMode)

            obj.name = prjName;
            obj.file = prjFile;
            obj.hash = prjHash;
        end

        %-----------------------------------------------------------------%
        function [ecdObj, msg] = load(obj, context, fileName, generalSettings, ecdObj)
            arguments
                obj
                context (1,:) char {mustBeMember(context, {'FILE', 'ECD'})}
                fileName
                generalSettings
                ecdObj
            end

            % Em 23/01/2026, a versão 1 do projeto contempla instâncias das 
            % classes model.ECD e model.Project. Ao ler um arquivo .mat, 
            % usando função "load", o MATLAB realiza validações simples, como
            % adicionar novas propriedades (com valores padrão) ou remover 
            % outras que não existem mais (independentemente do seu conteúdo). 

            % Foi mantido, por compatibilidade, "context" como argumento de 
            % entrada, viabilizando uso do mesmo módulo auxApp.dockReportLib
            % em vários apps (monitorSPED, SCH etc).

            try
                required = {'source', 'version', 'variables'};
                varsInFile = who('-file', fileName);
                if any(~ismember(required, varsInFile))
                    missing = setdiff(required, varsInFile);
                    error('Missing required variables: %s', strjoin(missing, ', '))
                end
                
                prjData = load(fileName, '-mat', required{:});
                
                if ~strcmp(class.Constants.appName, prjData.source)
                    error('File generated by a different application. Expected: %s. Found: %s.', class.Constants.appName, prjData.source)
                end
    
                switch prjData.version
                    case 1
                        restart(obj)

                        obj.name = prjData.variables.name;
                        obj.file = fileName;
                        obj.hash = prjData.variables.hash;

                        contextList = {'FILE', 'ECD'};
                        for ii = 1:numel(contextList)
                            context = contextList{ii};

                            if isfile(prjData.variables.modules.(context).generatedFiles.lastZIPFullPath)
                                try
                                    unzipFiles = unzip(prjData.variables.modules.(context).generatedFiles.lastZIPFullPath, generalSettings.fileFolder.tempPath);
                                    for jj = 1:numel(unzipFiles)
                                        [~, ~, unzipFileExt] = fileparts(unzipFiles{jj});
    
                                        switch lower(unzipFileExt)
                                            case '.html'
                                                obj.modules.(context).generatedFiles.lastHTMLDocFullPath = unzipFiles{jj};
                                            case '.json'
                                                obj.modules.(context).generatedFiles.lastJSONFullPath    = unzipFiles{jj};
                                            case '.xlsx'
                                                obj.modules.(context).generatedFiles.lastTableFullPath   = unzipFiles{jj};
                                        end
                                    end
                                    
                                    obj.modules.(context).generatedFiles.id              = prjData.variables.modules.(context).generatedFiles.id;
                                    obj.modules.(context).generatedFiles.lastZIPFullPath = prjData.variables.modules.(context).generatedFiles.lastZIPFullPath;
                                catch 
                                end
                            end
    
                            obj.modules.(context).ui.system = prjData.variables.modules.(context).ui.system;
                            obj.modules.(context).ui.unit   = prjData.variables.modules.(context).ui.unit;
                            obj.modules.(context).ui.issue  = prjData.variables.modules.(context).ui.issue;
                            obj.modules.(context).ui.entity = prjData.variables.modules.(context).ui.entity;
        
                            reportModel = prjData.variables.modules.(context).ui.reportModel;
                            if ismember(reportModel, obj.modules.(context).ui.templates)
                                obj.modules.(context).ui.reportModel = reportModel;
                            end
    
                            obj.modules.(context).uploadedFiles = [prjData.variables.modules.(context).uploadedFiles, obj.modules.(context).uploadedFiles];
                            [~, uniqueUploadedFilesIndexes] = unique({obj.modules.(context).uploadedFiles.hash});
                            obj.modules.(context).uploadedFiles = obj.modules.(context).uploadedFiles(uniqueUploadedFilesIndexes);
                        end

                        obj.issueDetails = [prjData.variables.issueDetails, obj.issueDetails];                        
                        
                        obj.entityDetails = [prjData.variables.entityDetails, obj.entityDetails];                        
                        [~, uniqueDetailsIndexes] = unique({obj.entityDetails.id});
                        obj.entityDetails = obj.entityDetails(uniqueDetailsIndexes);

                        % Pode ocorrer uma coincidência de fluxos que compõem
                        % o projeto e fluxos já lidos. Se evidenciado, serão
                        % mantidos os fluxos do projeto.
                        idx = ismember({ecdObj.Hash}, {prjData.variables.ecdData.Hash});
                        if any(idx)
                            delete(ecdObj(idx))
                            ecdObj(idx) = [];
                        end
    
                        ecdObj = [ecdObj, prjData.variables.ecdData];
    
                    otherwise
                        error('UnexpectedVersion')
                end
                msg = '';

            catch ME
                msg = ME.message;
            end
        end

        %-----------------------------------------------------------------%
        % ## INSS ##
        %-----------------------------------------------------------------%
        function [rate, msgError] = calculateInssRate(obj, state, period, rateType, numDecimals)
            arguments
                obj
                state    char {mustBeMember(state, {'AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO'})}
                period   datetime
                rateType char {mustBeMember(rateType, {'mean', 'eomonth'})} = 'mean'
                numDecimals double = 3
            end
            
            Year = year(period);
            Month = month(period);
            endOfMonthDay = eomday(Year, Month);

            % Identifica limites do período sob análise:
            beginOfPeriod = datetime([Year, Month, 1]);
            endOfPeriod   = datetime([Year, Month, endOfMonthDay]);

            try    
                % Identifica registros relacionados à UF indicada:
                indexes = find(strcmp(obj.inss.("UF"), state) & obj.inss.("Vigência") <= endOfPeriod);            
                if isempty(indexes)
                    error('Não identificado registro que possibilite calcular a alíquota vigente de INSS')
                end
    
                refINSSTable = obj.inss(indexes, :);
                switch rateType
                    case 'mean'
                        refNumDays = endOfMonthDay;            
                        rate = 0;
                        for ii = height(refINSSTable):-1:1
                            numDays    = refNumDays - day(max(refINSSTable.("Vigência")(ii), beginOfPeriod)) + 1;
                            rate   = rate + numDays * refINSSTable.("Alíquota máxima")(ii);
                            refNumDays = refNumDays - numDays;
                            if refNumDays <= 0
                                break
                            end
                        end
                        rate = rate/endOfMonthDay;
    
                    case 'eomonth'
                        rate = refINSSTable.("Alíquota máxima")(end);
                end
                msgError = '';

            catch ME
                index = find(strcmp(obj.inss.("UF"), state), 1);
                rate = obj.inss.("Alíquota máxima")(index);
                msgError = sprintf('[INSS Fallback] ∄ alíquota no domínio (%s, %s) ⇒ %.1f%%', state, endOfPeriod, 100 * rate);
            end

            rate = round(rate, numDecimals);
        end

        %-----------------------------------------------------------------%
        % ## VALIDATION ##
        %-----------------------------------------------------------------%
        function status = validateReportRequirements(obj, context, requirement)
            arguments
                obj 
                context   (1,:) char {mustBeMember(context, {'FILE', 'ECD'})} 
                requirement {mustBeMember(requirement, {'issue', 'unit', 'reportModel', 'entity'})}
            end
            switch requirement
                case 'issue'
                    issue  = obj.modules.(context).ui.issue;
                    status = (issue > 0) && (issue < inf);
                case 'unit'
                    status = ~isempty(obj.modules.(context).ui.unit);
                case 'reportModel'
                    status = ~isempty(obj.modules.(context).ui.reportModel);
                case 'entity'
                    entity = obj.modules.(context).ui.entity;
                    status = ~isempty(entity.type) && ~isempty(entity.name) && (strcmp(entity.type, 'Importador') || entity.status);
            end
        end

        %-----------------------------------------------------------------%
        % ## UPDATE ##
        %-----------------------------------------------------------------%
        function updateGeneratedFiles(obj, context, id, rawFiles, htmlFile, jsonFile, tableFile, zipFile)
            arguments
                obj
                context   (1,:) char {mustBeMember(context, {'FILE', 'ECD'})}
                id        char = ''
                rawFiles  cell = {}
                htmlFile  char = ''
                jsonFile  char = ''
                tableFile char = ''
                zipFile   char = ''
            end

            obj.modules.(context).generatedFiles.id                  = id;
            obj.modules.(context).generatedFiles.rawFiles            = rawFiles;
            obj.modules.(context).generatedFiles.lastHTMLDocFullPath = htmlFile;
            obj.modules.(context).generatedFiles.lastJSONFullPath    = jsonFile;
            obj.modules.(context).generatedFiles.lastTableFullPath   = tableFile;
            obj.modules.(context).generatedFiles.lastZIPFullPath     = zipFile;
        end

        %-----------------------------------------------------------------%
        function updateUploadedFiles(obj, context, system, issue, status)
            arguments
                obj
                context (1,:) char {mustBeMember(context, {'FILE', 'ECD'})}
                system
                issue
                status
            end

            obj.modules.(context).uploadedFiles(end+1) = struct( ...
                'hash', model.ProjectBase.computeUploadedFileHash(system, issue, status), ...
                'system', system, ...
                'issue', issue, ...
                'status', status, ...
                'timestamp', datestr(now) ...
            );
        end

        %-----------------------------------------------------------------%
        function updateUiInfo(obj, context, fieldName, fieldValue)
            arguments
                obj
                context    (1,:) char {mustBeMember(context, {'self', 'FILE', 'ECD'})}
                fieldName  (1,:) char
                fieldValue
            end

            switch fieldName
                case {'name', 'file', 'hash'}
                    obj.(fieldName) = fieldValue;

                case 'issueDetails'
                    [~, issueIndex] = ismember(fieldValue.issue, [obj.issueDetails.issue]);
                    if ~issueIndex
                        issueIndex = numel(obj.issueDetails) + 1;
                    end                    
                    obj.issueDetails(issueIndex) = fieldValue;

                case 'entityDetails'
                    [~, entityIdIndex] = ismember(fieldValue.id, {obj.entityDetails.id});
                    if ~entityIdIndex
                        entityIdIndex = numel(obj.entityDetails) + 1;
                    end                    
                    obj.entityDetails(entityIdIndex) = fieldValue;

                otherwise
                    obj.modules.(context).ui.(fieldName) = fieldValue;
            end
        end

        %-----------------------------------------------------------------%
        % ## GET ##
        %-----------------------------------------------------------------%
        function fileName = getGeneratedDocumentFileName(obj, fileExt, context)
            arguments
                obj
                fileExt (1,:) char {mustBeMember(fileExt, {'.html', '.json', '.xlsx', '.zip'})}
                context (1,:) char {mustBeMember(context, {'FILE', 'ECD'})}
            end

            switch fileExt
                case '.html'
                    fileName = obj.modules.(context).generatedFiles.lastHTMLDocFullPath;
                case '.json'
                    fileName = obj.modules.(context).generatedFiles.lastJSONFullPath;
                case '.xlsx'
                    fileName = obj.modules.(context).generatedFiles.lastTableFullPath;
                case '.zip'
                    fileName = obj.modules.(context).generatedFiles.lastZIPFullPath;
            end

            if ismember(fileExt, {'.html', '.zip'}) && ~isempty(fileName) && ~isfile(fileName)
                fileName = '';
                updateGeneratedFiles(obj, context)
            end
        end

        %-----------------------------------------------------------------%
        function uploadedFiles = getUploadedFiles(obj, context, system, issue)
            arguments
                obj
                context (1,:) char {mustBeMember(context, {'FILE', 'ECD'})}
                system
                issue
            end

            uploadedFiles = obj.modules.(context).uploadedFiles;
            if ~isempty(uploadedFiles)
                uploadedFiles = uploadedFiles(strcmp({uploadedFiles.system}, system) & [uploadedFiles.issue] == issue);
            end
        end

        %-----------------------------------------------------------------%
        function details = getIssueDetailsFromCache(obj, system, issue)
            detailsIndex = find(strcmp({obj.issueDetails.system}, system) & [obj.issueDetails.issue] == issue, 1);
            
            if ~isempty(detailsIndex)
                details  = obj.issueDetails(detailsIndex).details;
            else
                details  = '';
            end
        end

        %-----------------------------------------------------------------%
        function details = getEntityDetailsFromCache(obj, id)
            [~, entityIndex] = ismember(id, {obj.entityDetails.id});
            
            if entityIndex
                details = obj.entityDetails(entityIndex).details;
            else
                details = '';      
            end
        end

        %-----------------------------------------------------------------%
        % ## GET/FETCH ##
        %-----------------------------------------------------------------%
        function [details, msgError] = getOrFetchIssueDetails(obj, system, issue, eFiscalizaObj)
            details  = getIssueDetailsFromCache(obj, system, issue);
            msgError = '';

            if isempty(details)
                try
                    env = strsplit(system);
                    if isscalar(env)
                        env = 'PD';
                    else
                        env = env{2};
                    end
    
                    issueInfo = struct( ...
                        'type', 'ATIVIDADE DE INSPEÇÃO', ...
                        'id', issue ...
                    );
                    
                    response = run(eFiscalizaObj, env, 'queryIssue', issueInfo);
                    if isstruct(response)
                        details = struct( ...
                            'system', system, ...
                            'issue', issue, ...
                            'details', response, ...
                            'timestamp', datestr(now) ...
                        );
                        updateUiInfo(obj, 'self', 'issueDetails', details)
    
                    else
                        error(response)
                    end    
                catch ME
                    msgError = ME.message;
                end              
            end
        end

        %-----------------------------------------------------------------%
        function [details, msgError] = getOrFetchEntityDetails(obj, id)
            details  = getEntityDetailsFromCache(obj, id);
            msgError = '';

            if isempty(details)
                [entityId, ~, details, msgError] = checkCNPJOrCPF(id, 'PublicAPI');

                if ~isempty(details)
                    updateUiInfo(obj, 'self', 'entityDetails', struct('id', entityId, 'details', details, 'timestamp', datestr(now)))
                end                
            end
        end
    end


    methods (Access = private)
        %-----------------------------------------------------------------%
        function contextInitialization(obj, contextList, generalSettings)
            % O "id", do "generatedFiles", é a lista ordenada de "hashs" dos registros 
            % que compõem "inspectedProducts".

            obj.name = '';
            obj.file = '';
            obj.hash = '';

            for ii = 1:numel(contextList)
                context = contextList{ii};
                obj.modules.(context) = struct( ...
                    'annotationTable', [], ...
                    'generatedFiles', struct( ...
                        'id', '', ...
                        'rawFiles', {{}}, ...
                        'lastHTMLDocFullPath', '', ...
                        'lastJSONFullPath', '', ...
                        'lastTableFullPath', '', ...
                        'lastZIPFullPath', '' ...
                    ), ...
                    'uploadedFiles', struct( ...
                        'hash', {}, ...
                        'system', {}, ...
                        'issue', {}, ...
                        'status', {}, ...
                        'timestamp', {} ...
                    ), ...
                    'ui', struct( ...
                        'system', '', ...
                        'unit',   '',  ...
                        'issue',  -1,  ...
                        'templates', {{}}, ...
                        'reportModel', '',  ...
                        'reportVersion', 'Preliminar', ...
                        'entityTypes', {{}},  ...
                        'entity', struct( ...
                            'type', '', ...
                            'name', '', ...
                            'id',   '', ...
                            'status', false ...
                        ) ...
                    ) ...
                );

                obj.modules.(context).ui.entityTypes = generalSettings.ui.typeOfEntity.options;
                obj.modules.(context).ui.entity.type = generalSettings.ui.typeOfEntity.default;
            end

            readReportTemplatesFile(obj, obj.rootFolder)
        end

        %-----------------------------------------------------------------%
        function readReportTemplatesFile(obj, rootFolder)
            [projectFolder, ...
             programDataFolder] = appEngine.util.Path(class.Constants.appName, rootFolder);
            projectFilePath  = fullfile(projectFolder,     'ReportTemplates.json');
            externalFilePath = fullfile(programDataFolder, 'ReportTemplates.json');

            try
                if ~isdeployed()
                    error('ForceDebugMode')
                end
                obj.report.templates = jsondecode(fileread(externalFilePath));
            catch
                obj.report.templates = jsondecode(fileread(projectFilePath));
            end

            % Identifica lista de templates por módulo...
            contextList = fieldnames(obj.modules);
            templateNameList = {obj.report.templates.Name};

            for ii = 1:numel(contextList)
                templateIndexes = ismember({obj.report.templates.Module}, contextList(ii));
                obj.modules.(contextList{ii}).ui.templates = [{''}, templateNameList(templateIndexes)];
            end
        end
    end
    
end