classdef Project < model.ProjectCommon

    % ## model.Project (monitorSPED) ##      
    % PUBLIC
    %   ├── Project
    %   |   |── restart
    %   |   └── model.ProjectBase.readIcmsReferenceData
    %   ├── restart
    %   │   └── initialization (SuperClass)
    %   ├── checkIfUpdateNeeded
    %   │   └── model.ProjectBase.computeProjectHash
    %   ├── save
    %   │   └── model.ProjectBase.computeProjectHash
    %   ├── load
    %   │   └── restart
    %   └── calculateIcmsRate

    properties
        %-----------------------------------------------------------------%
        icms
    end


    methods
        %-----------------------------------------------------------------%
        function obj = Project(mainApp, rootFolder)
            obj@model.ProjectCommon(mainApp, rootFolder);

            restart(obj)
            obj.icms = model.ProjectBase.readIcmsReferenceData(rootFolder);
        end

        %-----------------------------------------------------------------%
        % ## LIFECYCLE MANAGEMENT ##
        %-----------------------------------------------------------------%
        function restart(obj, context)
            contextList = {'FILE', 'ECD', 'EFD'};
            initialization(obj, contextList, obj.mainApp.General)
        end

        %-----------------------------------------------------------------%
        function updateNeeded = checkIfUpdateNeeded(obj, ecdObj)
            updateNeeded = false;
            
            if ~isempty(obj.name)
                currentPrjHash = model.ProjectBase.computeProjectHash(obj.name, obj.file, ecdObj, obj.issueDetails, obj.entityDetails);
                updateNeeded   = ~isequal(obj.hash, currentPrjHash);
            end
        end

        %-----------------------------------------------------------------%
        function save(obj, context, prjName, prjFile, outputFileCompressionMode, ecdObj)
            arguments
                obj
                context (1,:) char {mustBeMember(context, {'FILE', 'ECD', 'EFD'})}
                prjName
                prjFile
                outputFileCompressionMode
                ecdObj
            end

            source    = class.Constants.appName;
            type      = 'ProjectData';
            version   = 1;
            userData  = [];

            prjHash   = model.ProjectBase.computeProjectHash(prjName, prjFile, ecdObj, obj.issueDetails, obj.entityDetails);
            variables = struct( ...
                'name',    prjName, ...
                'hash',    prjHash, ...
                'modules', obj.modules, ...
                'issueDetails', obj.issueDetails, ...
                'entityDetails', obj.entityDetails, ...
                'ecdData', ecdObj ...
            );

            compressionMode = {};
            if strcmp(outputFileCompressionMode, 'Não')
                compressionMode = {'-nocompression'};
            end

            save(prjFile, 'source', 'type', 'version', 'variables', 'userData', '-mat', '-v7', compressionMode{:})

            obj.name = prjName;
            obj.file = prjFile;
            obj.hash = prjHash;
        end

        %-----------------------------------------------------------------%
        function [ecdObj, msg] = load(obj, context, fileName, generalSettings, ecdObj)
            arguments
                obj
                context (1,:) char {mustBeMember(context, {'FILE', 'ECD', 'EFD'})}
                fileName
                generalSettings
                ecdObj
            end

            % Em 23/01/2026, a versão 1 do projeto contempla instâncias das 
            % classes model.ECD e model.Project. Ao ler um arquivo .mat, 
            % usando função "load", o MATLAB realiza validações simples, como
            % adicionar novas propriedades (com valores padrão) ou remover 
            % outras que não existem mais (independentemente do seu conteúdo). 

            % Foi mantido, por compatibilidade, "context" como argumento de 
            % entrada, viabilizando uso do mesmo módulo auxApp.dockReportLib
            % em vários apps (monitorSPED, SCH etc).

            try
                required = {'source', 'version', 'variables'};
                varsInFile = who('-file', fileName);
                if any(~ismember(required, varsInFile))
                    missing = setdiff(required, varsInFile);
                    error('Missing required variables: %s', strjoin(missing, ', '))
                end
                
                prjData = load(fileName, '-mat', required{:});
                
                if ~strcmp(class.Constants.appName, prjData.source)
                    error('File generated by a different application. Expected: %s. Found: %s.', class.Constants.appName, prjData.source)
                end
    
                switch prjData.version
                    case 1
                        restart(obj)

                        obj.name = prjData.variables.name;
                        obj.file = fileName;
                        obj.hash = prjData.variables.hash;

                        contextList = {'FILE', 'ECD', 'EFD'};
                        for ii = 1:numel(contextList)
                            context = contextList{ii};

                            if isfile(prjData.variables.modules.(context).generatedFiles.lastZIPFullPath)
                                try
                                    unzipFiles = unzip(prjData.variables.modules.(context).generatedFiles.lastZIPFullPath, generalSettings.fileFolder.tempPath);
                                    for jj = 1:numel(unzipFiles)
                                        [~, ~, unzipFileExt] = fileparts(unzipFiles{jj});
    
                                        switch lower(unzipFileExt)
                                            case '.html'
                                                obj.modules.(context).generatedFiles.lastHTMLDocFullPath = unzipFiles{jj};
                                            case '.json'
                                                obj.modules.(context).generatedFiles.lastJSONFullPath    = unzipFiles{jj};
                                            case '.xlsx'
                                                obj.modules.(context).generatedFiles.lastTableFullPath   = unzipFiles{jj};
                                            case '.teams'
                                                obj.modules.(context).generatedFiles.lastTEAMSFullPath   = unzipFiles{jj};
                                        end
                                    end
                                    
                                    obj.modules.(context).generatedFiles.id              = prjData.variables.modules.(context).generatedFiles.id;
                                    obj.modules.(context).generatedFiles.lastZIPFullPath = prjData.variables.modules.(context).generatedFiles.lastZIPFullPath;
                                catch 
                                end
                            end
    
                            obj.modules.(context).ui.system = prjData.variables.modules.(context).ui.system;
                            obj.modules.(context).ui.issue  = prjData.variables.modules.(context).ui.issue;
                            obj.modules.(context).ui.entity = prjData.variables.modules.(context).ui.entity;
                            
                            unit = prjData.variables.modules.(context).ui.unit;
                            if ~isempty(unit) && ismember(unit, generalSettings.eFiscaliza.defaultValues.unit)
                                obj.modules.(context).ui.unit = unit;
                            end
        
                            reportModel = prjData.variables.modules.(context).ui.reportModel;
                            if ismember(reportModel, obj.modules.(context).ui.templates)
                                obj.modules.(context).ui.reportModel = reportModel;
                            end
    
                            obj.modules.(context).uploadedFiles = [prjData.variables.modules.(context).uploadedFiles, obj.modules.(context).uploadedFiles];
                            [~, uniqueUploadedFilesIndexes] = unique({obj.modules.(context).uploadedFiles.hash});
                            obj.modules.(context).uploadedFiles = obj.modules.(context).uploadedFiles(uniqueUploadedFilesIndexes);
                        end

                        obj.issueDetails = [prjData.variables.issueDetails, obj.issueDetails];                        
                        
                        obj.entityDetails = [prjData.variables.entityDetails, obj.entityDetails];                        
                        [~, uniqueDetailsIndexes] = unique({obj.entityDetails.id});
                        obj.entityDetails = obj.entityDetails(uniqueDetailsIndexes);

                        % Registra nome do arquivo do projeto (.MAT), assim 
                        % como índice do objeto, possibilitando releitura dos 
                        % dados na mesma sessão do app.
                        for kk = 1:numel(prjData.variables.ecdData)
                            prjData.variables.ecdData(kk).GUI.loadedFile.Name = fileName;
                            prjData.variables.ecdData(kk).GUI.loadedFile.Index = kk;
                        end

                        % Pode ocorrer uma coincidência de fluxos que compõem
                        % o projeto e fluxos já lidos. Se evidenciado, serão
                        % mantidos os fluxos do projeto.
                        idx = ismember({ecdObj.Hash}, {prjData.variables.ecdData.Hash});
                        if any(idx)
                            delete(ecdObj(idx))
                            ecdObj(idx) = [];
                        end
    
                        ecdObj = [ecdObj, prjData.variables.ecdData];
                        model.ECDBase.ensureTableSchema(ecdObj, generalSettings);
    
                    otherwise
                        error('UnexpectedVersion')
                end
                msg = '';

            catch ME
                msg = ME.message;
            end
        end

        %-----------------------------------------------------------------%
        % ## ICMS ##
        %-----------------------------------------------------------------%
        function [rate, msgError] = calculateIcmsRate(obj, state, period, rateType, numDecimals)
            arguments
                obj
                state    char {mustBeMember(state, {'AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO'})}
                period   datetime
                rateType char {mustBeMember(rateType, {'mean', 'eomonth'})} = 'mean'
                numDecimals double = 3
            end
            
            Year = year(period);
            Month = month(period);
            endOfMonthDay = eomday(Year, Month);

            % Identifica limites do período sob análise:
            beginOfPeriod = datetime([Year, Month, 1]);
            endOfPeriod   = datetime([Year, Month, endOfMonthDay]);

            try    
                % Identifica registros relacionados à UF indicada:
                indexes = find(strcmp(obj.icms.("UF"), state) & obj.icms.("Vigência") <= endOfPeriod);            
                if isempty(indexes)
                    error('Não identificado registro que possibilite calcular a alíquota vigente de ICMS')
                end
    
                refICMSTable = obj.icms(indexes, :);
                switch rateType
                    case 'mean'
                        refNumDays = endOfMonthDay;            
                        rate = 0;
                        for ii = height(refICMSTable):-1:1
                            numDays = refNumDays - day(max(refICMSTable.("Vigência")(ii), beginOfPeriod)) + 1;
                            rate = rate + numDays * refICMSTable.("Alíquota máxima")(ii);
                            refNumDays = refNumDays - numDays;
                            if refNumDays <= 0
                                break
                            end
                        end
                        rate = rate/endOfMonthDay;
    
                    case 'eomonth'
                        rate = refICMSTable.("Alíquota máxima")(end);
                end
                msgError = '';

            catch ME
                index = find(strcmp(obj.icms.("UF"), state), 1);
                rate = obj.icms.("Alíquota máxima")(index);
                msgError = sprintf('[ICMS Fallback] ∄ alíquota no domínio (%s, %s) ⇒ %.1f%%', state, endOfPeriod, 100 * rate);
            end

            rate = round(rate, numDecimals);
        end
    end

end