classdef (Abstract) Constants

    properties (Constant)
        %-----------------------------------------------------------------%
        appName       = 'monitorSPED'
        appVersion    = '1.01.3'

        windowSize    = [1244, 660]
        windowMinSize = [ 950, 660]
    end

    
    methods (Static = true)
        %-----------------------------------------------------------------%
        function d = english2portuguese()
            names  = ["AccountEntryHistoryCount", ...
                      "AccountEntryHistoryUniqueValues", ...
                      "AccountEntryHistoryWarning", ...
                      "FileName", ...
                      "TempFileName", ...
                      "Period", ...
                      "Content", ...
                      "FullDescription", ...
                      "Table", ...
                      "ReceitaFederal", ...
                      "OrdinaryTable", ...
                      "Origin", ...
                      "ReadOrdinaryTable", ...
                      "CreateCustomTable", ...
                      "Warnings", ...
                      "UF"];
            
            values = ["SUMÁRIO DE LANÇAMENTOS", ...
                      "LANÇAMENTOS NORMALIZADOS DEDUPLICADOS (1º REGISTRO DE CADA GRUPO)", ...
                      "HISTÓRICO DE LANÇAMENTOS", ...
                      "Arquivo", ...
                      "Arquivo temporário", ...
                      "Período", ...
                      "Conteúdo", ...
                      "Árvore de descrição da conta", ...
                      "Registros", ...
                      "Receita Federal", ...
                      "Registros ordinários", ...
                      "Origem", ...
                      "Registros ordinários lidos", ...
                      "Tabelas customizadas", ...
                      "Alertas do processo de leitura", ...
                      "Unidade da Federação"];
        
            d = dictionary(names, values);
        end

        %-----------------------------------------------------------------%
        function d = ufMapping()
            names  = ["AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", ...
                      "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", ...
                      "RS", "RO", "RR", "SC", "SP", "SE", "TO"];
            
            values = ["Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", ...
                      "Espírito Santo", "Goiás","Maranhão", "Mato Grosso", "Mato Grosso do Sul",    ...
                      "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí",           ...
                      "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia",     ...
                      "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins"];
            
            d = dictionary(names, values);
        end
    end
end