classdef (Abstract) Constants

    properties (Constant)
        %-----------------------------------------------------------------%
        appName       = 'monitorSPED'
        appRelease    = 'R2024a'
        appVersion    = 'alpha_4.01.0'

        windowSize    = [1244, 660]
        windowMinSize = [ 950, 660]
    end

    
    methods (Static = true)
        %-----------------------------------------------------------------%
        function fileName = DefaultFileName(userPath, Prefix, Issue)
            fileName = fullfile(userPath, sprintf('%s_%s', Prefix, datestr(now,'yyyy.mm.dd_THH.MM.SS')));

            if Issue > 0
                fileName = sprintf('%s_%d', fileName, Issue);
            end
        end

        %-----------------------------------------------------------------%
        function d = english2portuguese()
            names  = ["AccountHistoric", ...
                      "FileName", ...
                      "TempFileName", ...
                      "Period", ...
                      "Content", ...
                      "FullDescription", ...
                      "Table", ...
                      "ReceitaFederal", ...
                      "OrdinaryTable", ...
                      "Origin", ...
                      "ReadOrdinaryTable", ...
                      "CreateCustomTable", ...
                      "Warnings", ...
                      "UF"];
            values = ["Histórico completo da partida", ...
                      "Arquivo", ...
                      "Arquivo temporário", ...
                      "Período", ...
                      "Conteúdo", ...
                      "Árvore de descrição da conta", ...
                      "Registros", ...
                      "Receita Federal", ...
                      "Registros ordinários", ...
                      "Origem", ...
                      "Registros ordinários lidos", ...
                      "Tabelas customizadas", ...
                      "Alertas do processo de leitura", ...
                      "Unidade da Federação"];
        
            d = dictionary(names, values);
        end

        %-----------------------------------------------------------------%
        function d = ufMapping()
            names  = ["AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", ...
                      "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", ...
                      "RS", "RO", "RR", "SC", "SP", "SE", "TO"];
            
            values = ["Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", ...
                      "Espírito Santo", "Goiás","Maranhão", "Mato Grosso", "Mato Grosso do Sul",    ...
                      "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí",           ...
                      "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia",     ...
                      "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins"];
            
            d = dictionary(names, values);
        end

        %-----------------------------------------------------------------%
        function winMinSize = WindowMinSize(auxiliarApp)
            switch auxiliarApp
                case 'CONFIG'
                    winMinSize = [760, 588];
            end
        end
    end
end