function hAxes = axesCreationController(hPlotPanel)
    hParent = tiledlayout(hPlotPanel, 1, 1, 'Padding', 'compact');
    
    hAxes = uiaxes( ...
        hParent, ...
        'Color', [.07,0,0], 'TickDir', 'none', ...
        'FontName', 'Helvetica', 'FontSize', 10, 'XColor', [.8,.8,.8], 'YColor', [.8,.8,.8], ...
        'XTickLabel', {}, 'YTickLabel', {}, 'XAxisLocation', 'origin', ...
        'Interactions', dataTipInteraction, 'Toolbar', [] ...
    );

    hold(hAxes, "on")
end